### ISSUE TITLE
Search for Client Leads to Last Entry

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#25] opened 2019-04-08 23:27 UTC
When i search for a client and  they are not found, I then go to add Human and program  goes to last human entry. I have to refresh whole program and login again.

**Comment by carl-hamlin** [comment] 2019-04-08 23:33
When you say it goes to the last human entry, are you referring to the fact that the last name that you entered into search is there in the entry form as the proposed last name for the new entry?

**Comment by Lenorebarton** [comment] 2019-04-09 00:01
Yes except all the info from the last completed entry shows up, address
email etc.  I can’t add phone# nor submit next human without refreshing
then logging in again.  Very time consuming

**Comment by carl-hamlin** [comment] 2019-04-09 00:18
That sounds supremely annoying. I can't make it happen on my end, so at some point tomorrow let's see if we can make it happen on the machine up front in Valley Springs.

**Comment by carl-hamlin** [comment] 2019-04-09 23:16
@Lenorebarton  - I've tried all sorts of ways today to try and make this happen, and I can't reproduce it on my end. I'm going to close this bug out, but if you can make it happen again, please feel free to re-open this bug and append a description of what you did and how you did it. Thanks!

**Comment by carl-hamlin** [comment] 2019-04-10 19:42
I was able to make it happen again.

Apparently, the road to reproducing this issue involves adding a new client with multiple animals, then running a search on an existing client, also with multiple animals, then going back and trying to add another new client.

This issue and **Bug #13: Search Interfering with Intake** are very likely related.

**Comment by lwilsonbooth** [comment] 2019-04-15 20:42
Any progress? I'm having to login between entries.

**Comment by carl-hamlin** [comment] 2019-06-08 00:29
Fixes during the sabbatical prior to Round II implementation resolved this issue transparently.

**Closed by carl-hamlin** 2019-06-08 00:29 UTC
Labels: bug
