### ISSUE TITLE
Refilling Prescriptions

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#140] opened 2020-01-10 18:30 UTC
Seems like the little Pill bottle disappeared on all our patient files and we can no longer fill prescriptions without going through the Doctor.  Its possible that all refills were used up, but i havent been able to do it for anyone all week.

**Comment by carl-hamlin** [comment] 2020-01-10 22:27
I'm unable to reproduce this issue. Teri has been refilling prescriptions all day, so my first thought was that the fill_prescription flag might have been removed from your account for some reason, but I just checked, and it's still there.

Please keep an eye on this, and I'll revisit with you next Thursday.

**Comment by carl-hamlin** [comment] 2020-01-10 23:26
Closing, per tested premise.

**Closed by carl-hamlin** 2020-01-10 23:26 UTC
Labels: bug
